default_prompt:
  system: "You are a helpful assistant."
  user: |
    The following text contains information extracted from a video. Please provide a concise summary.
    
    {frame_captions}
    {transcript}

custom_prompts:
  "slate":
    system: "You are a helpful assistant specialized in formatting slates."
    user: |
      {frame_captions}
      Extract the slate information and format it as JSON key-value pairs. Return only the JSON object.
  "chyron":
    system: "You are a helpful assistant."
    user: |
      {frame_captions}
      {transcript}
      Given the frame captions and transcript, who is shown in this segment?

# Apply JSON extraction postprocessing to clean up Llama output
postprocessor: "json_extractor"

context_config:
  input_context: "timeframe"  # Options: "timeframe", "timepoint", "fixed_window"

  apps:
    "http://apps.clams.ai/app-llava-captioner/v1": "frame_captions"
    "http://apps.clams.ai/app-whisper-wrapper/v1": "transcript"

  timeframe:
    app_uri: "http://apps.clams.ai/app-swt-detection/"
    label_mapping:
      "slate": "slate"
      "chyron": "chyron"